PIUnivesp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),  
    path('', include("biblioteca.urls", namespace="biblioteca")), 
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblioteca/urls.py
from sys import setswitchinterval
from django.urls import path
from django.urls.resolvers import URLPattern
from django.contrib.staticfiles.urls import static


from . import views

app_name = "biblioteca"

urlpatterns = [
    path('', views.Home.as_view(), name = "index"),
    path('biblioteca/', views.BooksListView.as_view(), name = "list"),
    path("biblioteca/<slug:slug>/", views.BooksDeitalView.as_view(), name = "detail"),
    path('termsOfService/', views.TermsOfService.as_view(), name = 'termsOfService'), 
]

biblioteca/models.py
from django.db import models
from django.db.models.fields import NullBooleanField


# Create your models here.

class Books(models.Model):
    title = models.CharField(max_length=225)
    slug = models.SlugField(max_length=255, unique = True)
    author = models.CharField(max_length=100)
    body = models.TextField()
    bookPhoto = models.ImageField(upload_to = "books_Img/", null = True, blank = True)
    link = models.CharField(max_length=255, default= NullBooleanField)

    def __str__(self):
        return self.title

biblioteca/views.py
from django.views.generic import DetailView, ListView, TemplateView

from .models import Books

class BooksListView(ListView):
    model = Books

class BooksDeitalView(DetailView):
    model = Books

class Home(TemplateView):
    template_name = './biblioteca/index.html'

class TermsOfService(TemplateView):
    template_name = './biblioteca/termsOfService.html'

biblioteca/templates/biblioteca/baseDetail.html
{% load static %}

<!DOCTYPE html>

<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/books_detail.css' %}" rel = "stylesheet">
</head>

<body>
    <header>
        <div class="logo"><img src="{% static 'img/logo_univesp.png'%}"/></div><!--logo-->
        <div class ="titulo">
            <h1><a class='a1' href="../">Biblioteca Digital de Taquaral</a></h1>
        </div><!--titulo-->
        <div class="logo2"><img src="{% static 'img/logo_compartilhar.png'%}"/></div><!--logo2-->
    </header>

    <main>
        <div class="tituloEAutor">
        {% block content %}
        {% endblock %}
        </div>
    </main>
</body>

</html>

biblioteca/templates/biblioteca/baseList.html
{% load static %}

<!DOCTYPE html>

<html lang="pt-br">

<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/books_list.css' %}" rel = "stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
</head>

<body>

    <header>
        <div class="logo"><img src="{% static 'img/logo_univesp.png'%}"/></div><!--logo-->
        <div class ="titulo">
            <h1><a class='a1' href="../">Biblioteca Digital de Taquaral</a></h1>
        </div><!--titulo-->
        <div class="logo2"><img src="{% static 'img/logo_compartilhar.png'%}"/></div><!--logo2-->
    </header>



    <main>
        <p>Confira nossa lista de títulos:</p>

        <br><br><br>

    <div class="conteudoCentral">

    <div class="imagemEsquerda">


    <div class="listaDeLivros">
        {% block content %}
        {% endblock %}
    </div><!--listaDeLivros-->



    </div><!--conteudoCentral-->

    </main>
</body>

</html>

biblioteca/templates/biblioteca/books_detail.html
{% extends "biblioteca/baseDetail.html" %}

{% block title %} {{ books.title }} {% endblock %}  

{% block content %} 

    <h2>{{ books.title }}</h2>
    <h3>{{ books.author }}</h3>
    <br><br>

    <div class ="corpoDoTexto">
    {{ books.body|linebreaks }}
    </div><!--corpoDoTexto-->  

    <br><br>
    <p class="cliqueNaImagem">Clique na imagem abaixo para acessar o livro</p>
    <br>
    <div class = "imgContainer">
        <a href = "{{books.link}}"><img src="{{ books.bookPhoto.url }}"></a>
    </div>    


{% endblock %}

biblioteca/templates/biblioteca/books_list.html
{% extends "biblioteca/baseList.html" %}

{% block title %} Biblioteca Digital Taquaral (SP) {% endblock %} 


{% block content %} 

    {% for books in books_list %}
        <article>
            <li><a href = "{{books.slug}}">{{books.title}}</a></li>
            <br>
        </article>
    {% endfor %}


{% endblock %}

biblioteca/templates/biblioteca/index.html
{% load static %}

<!DOCTYPE html>

<html lang="pt-br">

<head>  
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteca Digital Taquaral-SP</title>
    <link href="{% static 'css/front-page.css' %}" rel = "stylesheet">
</head>
<body>
    <header>
        <div class="center">
            <div class="logo"><img src="{% static 'img/logo_univesp.png'%}"/></div><!--logo-->
            <div class ="titulo">
                <h1>Biblioteca Digital de Taquaral</h1>
            </div><!--titulo-->
            <div class="logo2"><img src="{% static 'img/logo_compartilhar.png'%}"/></div><!--logo2-->
            
            <div class="corpo">

                <h2 class="subtitulo">Bem-vindo à Biblioteca Digital do Município de Taquaral-SP
                </h2> <!--subtitulo-->
                
                <div class = "texto">A Prefeitura Municipal de Taquaral-SP, por meio de seu site, disponibiliza a Biblioteca Digital Municipal, um canal de acesso digital a um acervo multidisciplinar, totalmente digital e relevante de livros escolares e acadêmicos para fins culturais, pedagógicos e educacionais. 
                A partir da seção “Biblioteca Online”, o indivíduo interessado consegue consultar o acervo disponível, entrar em contato com os responsáveis pelos livros disponibilizados no site e fazer o download dos livros de seu interesse.
                O acervo conta com títulos clássicos da literatura nacional e internacional, livros didáticos, dicionários, livros infantis, infanto-juvenis, trilogias e uma diversidade de gêneros.
                Agilizando essa prestação de serviços e proporcionando maior interação entre a Biblioteca Digital Municipal e seus usuários, a Prefeitura Municipal de Taquaral-SP espera que crianças, jovens, adultos e familiares possam usufruir de bons momentos de leitura e de enriquecimento pessoal e cultural.
                

                        <div class = "marca-dagua">

        </div><!--marca-dagua--> 
        </div><!--texto-->
        </div><!--corpo-->
        </div><!--center-->

        <div class = "textoCliqueAqui">
    
            <span class="cliqueAqui"><a href="biblioteca/">Clique aqui</a></span> para consultar o acervo da Biblioteca Online
            <br><br>
            <span class="cliqueAqui"><a href="termsOfService/">Clique aqui</a></span> para saber os Termos de Uso da Biblioteca Digital Municipal
        </div><!--textoCliqueAqui-->
        <div class="blocoImagemCriancas"><img src = "{% static 'img/criancas_lendo.png' %}"/></div><!--imagemCriancas-->

    </header>

    </body>
</html>

biblioteca/templates/biblioteca/termsOfService.html
{% load static %}

<!DOCTYPE html>

<html lang="pt-br">

<head>  
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteca Digital Taquaral-SP</title>
    <link href="{% static 'css/termsOfService.css' %}" rel = "stylesheet">
</head>
    <header>
        <div class="center">
            <div class="logo"><img src="{% static 'img/logo_univesp.png'%}"/></div><!--logo-->
            <div class ="titulo">
                <h1><a class='a1' href="../">Biblioteca Digital de Taquaral</a></h1>
        </div><!--titulo-->
            <div class="logo2"><img src="{% static 'img/logo_compartilhar.png'%}"/></div><!--logo2-->
        </div><!--center--> 
    </header>
    <body>
        
        <main>
<h2>Termos de uso do Site</h2> 
<br><br>
<p>1.	Restrições de Uso</p>
<br>
Este site pertence á Prefeitura Municipal de Taquaral-SP e possui material que é derivado em parte ou no todo de materiais enviados por diversas pessoas, instituições e empresas, e é protegido pelas leis internacionais de direitos autorais e patentes. Você não é autorizado a alterar, copiar, reproduzir, transmitir ou distribuir em nenhuma forma qualquer material deste site (incluindo códigos, textos, imagens e programas) sem prévia autorização permitida pelos responsáveis do site. 
<br><br>
<p>2.	Privacidade</p>
<br>
A Prefeitura Municipal de Taquaral-SP se reserva ao direito de enviar e-mails para todos os cadastrados de acordo com as preferências selecionadas na hora do cadastro, bem como para todos os cadastrados, independente das preferências, se assim achar necessário para a divulgação do site. 
A qualquer momento a pessoa interessada poderá solicitar a sua retirada da lista ou solicitar alteração dos seus dados.
A Prefeitura Municipal de Taquaral-SP considera os emails como informações confidenciais, e não irá utilizá-los para nenhum outro propósito que não esteja de acordo com o segmento educacional, pedagógico e cultural em questão ou disponibilizá-los de qualquer forma para qualquer empresa, pessoa ou entidade. 
<br><br>
<p>3.	Responsabilidade</p>
<br>
A Prefeitura Municipal de Taquaral-SP tentará fazer todo o possível para que o conteúdo do site esteja sempre atualizado e contenha informações corretas. Entretanto, sob circunstância nenhuma, incluindo, mas não limitado a negligência, a Prefeitura Municipal de Taquaral (SP) será responsável por qualquer dano direto ou indireto, por acidente ou por consequência, que resulte do uso do material do site. 
<br><br>
<p>4.	Duração</p>
<br>
Este acordo se torna efetivo a partir do momento em que você se cadastra no site da Biblioteca Digital Municipal, tendo lido-o ou não, até quando a Prefeitura Municipal de Taquaral (SP) assim o desejar. O término desse acordo poderá ser realizado sem prévio aviso. No caso de término de acordo, o indivíduo não será mais autorizado a acessar qualquer área do site da Biblioteca Digital Municipal.   

        </main>
    </body>
</html>